# Generated by Django 5.2.14 on 2026-05-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrecioMineral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("ORO", "Oro"),
                            ("CARBON", "Carbón"),
                            ("NIQUEL", "Níquel"),
                            ("COBRE", "Cobre"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Mineral",
                    ),
                ),
                (
                    "precio_cop",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio (COP)"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de Cotización")),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro en Sistema"
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de Mineral",
                "verbose_name_plural": "Historial de Precios",
                "ordering": ["-fecha"],
            },
        ),
    ]
