# Generated by Django 5.2.14 on 2026-05-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preciomineral",
            name="unidad_medida",
            field=models.CharField(
                choices=[("GRAMO", "Gramo"), ("KILOGRAMO", "Kilogramo")],
                default="KILOGRAMO",
                max_length=15,
                verbose_name="Unidad de Medida",
            ),
        ),
    ]
